### ISSUE TITLE
Something is missing...

### ISSUE THREAD

**Issue by karelnet** [yiisoft/yii2-bootstrap4#107]
### What steps will reproduce the problem?
Install yii2 with basic config
Install bootstrap4 extension
Change asset import in main.php with bootstrap4 instead of boostrap
Generate a simple CRUD

### What's expected?
Form validation error showing "red" message
glyph icons showing in table

### What do you get instead?
Form validation stays black with message "cannot be blank"
glyph icons not showing

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.14
| PHP version      |7.1.12
| Operating system |Windows 10 (WAMP)

**Comment by machour** [comment]
1. For glyph, it's normal since they were dropped from bootstrap4 : https://getbootstrap.com/docs/4.0/migration/#components

2. For forms, did you change all your namespaces to use the news version? (ie. \yii\bootstrap4\ActiveForm instead \yii\bootstrap\ActiveForm)

Migrating from bootstrap 3 to bootstrap 4 isn't just a matter of changing the required library in your composer.json & assets. 

You may be interested in looking at this pull request that proposed to change yii2-app-basic to use bootstrap 4: https://github.com/yiisoft/yii2-app-basic/pull/191/files

**Comment by karelnet** [comment]
Thanks a lot, it helped me.
